### ISSUE TITLE
Humanoid Track

### ISSUE THREAD

**Issue by wellzito** [creativeIKEP/HolisticBarracuda#1]
I would like to exchange the points, for a humanoid model, to make an avatar body tracking that records the animations. How can I replace points by template?

**Comment by creativeIKEP** [comment]
Hello, @wellzito .
I can't support your request because HolisticBarracuda is the softwere that provide pose data only .
However, I am planing to develop avatar body tracking softwere. (https://github.com/creativeIKEP/BlazePoseBarracuda/issues/2 )
Thanks.

**Comment by wbdsnx** [comment]
@creativeIKEP  Do you have avatar body tracking demo now? Please!!!!

**Comment by creativeIKEP** [comment]
I have released an application that moves avatars. Please try using it.
https://github.com/creativeIKEP/HolisticMotionCapture
