### ISSUE TITLE
get resource from camera

### ISSUE THREAD

**Issue by ZHENSU** [creativeIKEP/HolisticBarracuda#2]
hi. I want to use the code with open my  pc camera, but i do not know how could i get the video resources from camera?

**Comment by creativeIKEP** [comment]
Hello, @ZHENSU .
Input images of the demo code are provided from [WebCamInput.cs](https://github.com/creativeIKEP/HolisticBarracuda/blob/4451dbb4abb9ac7d5de44b6f0794df3c3d4610fb/Assets/Scripts/WebCamInput.cs).
This code use the video resources from the `webCamName` variable name camera if the `staticInput` Texture variable is null.
Thanks.

**Comment by creativeIKEP** [comment]
I believe this issue is resolved.
I close this issue.
