### ISSUE TITLE
Use GPU

### ISSUE THREAD

**Issue by Zumbalamambo** [creativeIKEP/HolisticBarracuda#3]
`Feature request`

Please enable GPU mode.

**Comment by wbdsnx** [comment]
Any Solution? @Zumbalamambo

**Comment by Zumbalamambo** [comment]
@wbdsnx thank you! This repo is not maintained anymore. Please use the "MediapipeUnityPlugin".

**Comment by creativeIKEP** [comment]
@Zumbalamambo 
HolisticBarracuda predicts landmarks by using GPU...
HolisticBarracuda  does a lot of processes  in ComputeShaders (see [here](https://github.com/creativeIKEP/HolisticBarracuda/tree/main/Packages/HolisticBarracuda/ComputeShader) directory.

**Comment by creativeIKEP** [comment]
> This repo is not maintained anymore. Please use the "MediapipeUnityPlugin".

Sorry, I've been busy lately, so I couldn't do the maintenance.
I am improving it little by little, you can see the latest code in the [develop branch](https://github.com/creativeIKEP/HolisticBarracuda/tree/develop).

**Comment by creativeIKEP** [comment]
I believe this issue is resolved.
I close this issue.
